# packages in environment at /Users/akulesa/anaconda/envs/interactive:
#
# Name                    Version                   Build  Channel
anaconda                  custom           py27h2cfa9e9_0  
appnope                   0.1.0                    py27_0    conda-forge
backports                 1.0              py27hb4f9756_1  
backports.functools_lru_cache 1.5                      py27_1  
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
backports_abc             0.5              py27h6972548_0  
bleach                    2.1.3                      py_0    conda-forge
bokeh                     0.12.15                  py27_0  
bqplot                    0.11.1                   py27_0    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py27_0  
click                     6.7              py27h2b86a94_0  
cloudpickle               0.5.2                    py27_1  
configparser              3.5.0                    py27_0    conda-forge
cycler                    0.10.0           py27hfc73c78_0  
cytoolz                   0.9.0.1          py27h1de35cc_0  
dask                      0.17.2                   py27_0  
dask-core                 0.17.2                   py27_0  
decorator                 4.2.1                    py27_0  
distributed               1.21.4                   py27_0  
entrypoints               0.2.3                    py27_1    conda-forge
enum34                    1.1.6                    py27_1    conda-forge
freetype                  2.8                  h12048fb_1  
functools32               3.2.3.2          py27h8ceab06_1  
futures                   3.2.0            py27h1b80678_0  
heapdict                  1.0.0                    py27_2  
html5lib                  1.0.1                      py_0    conda-forge
icu                       58.2                          0    conda-forge
imageio                   2.3.0                    py27_0  
intel-openmp              2018.0.0                      8  
ipykernel                 4.8.2                    py27_0    conda-forge
ipython                   5.6.0                    py27_0    conda-forge
ipython_genutils          0.2.0                    py27_0    conda-forge
ipywidgets                7.4.0                      py_0    conda-forge
jinja2                    2.10             py27h70b8dc5_0  
jpeg                      9b                   he5867d9_2  
jsonschema                2.6.0                    py27_1    conda-forge
jupyter_client            5.2.3                    py27_0    conda-forge
jupyter_contrib_core      0.3.3                    py27_1    conda-forge
jupyter_contrib_nbextensions 0.5.0                    py27_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_highlight_selected_word 0.2.0                    py27_0    conda-forge
jupyter_latex_envs        1.4.4                    py27_0    conda-forge
jupyter_nbextensions_configurator 0.4.0                    py27_0    conda-forge
kiwisolver                1.0.1            py27h9856860_0  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1                  hb4e282d_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                          0    conda-forge
libpng                    1.6.34               he12f830_0  
libsodium                 1.0.16                        0    conda-forge
libtiff                   4.0.9                h0dac147_0  
libxml2                   2.9.8                         0    conda-forge
libxslt                   1.1.32                        0    conda-forge
locket                    0.2.0            py27ha10513d_1  
lxml                      4.2.1                    py27_0    conda-forge
markupsafe                1.0              py27hd3c86fa_1  
matplotlib                2.2.2            py27ha7267d0_0  
mistune                   0.8.3                    py27_1    conda-forge
mkl                       2018.0.2                      1  
msgpack-python            0.5.6            py27h04f5b5a_0  
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py27_0    conda-forge
ncurses                   6.0                  hd04f020_2  
networkx                  2.1                      py27_0  
notebook                  5.4.1                    py27_0    conda-forge
numpy                     1.11.3           py27h8a80b8c_4  
olefile                   0.45.1                   py27_0  
openssl                   1.0.2o               h26aff7b_0  
packaging                 17.1                     py27_0  
pandas                    0.22.0           py27h0a44026_0  
pandoc                    2.1.3                         0    conda-forge
pandocfilters             1.4.2                    py27_0    conda-forge
partd                     0.3.8            py27h7560dbf_0  
pathlib2                  2.3.2                    py27_0    conda-forge
patsy                     0.5.0                    py27_0  
pexpect                   4.5.0                    py27_0    conda-forge
pickleshare               0.7.4                    py27_0    conda-forge
pillow                    5.0.0            py27hfcce615_0  
pip                       9.0.1                    py27_5  
prompt_toolkit            1.0.15                   py27_0    conda-forge
psutil                    5.4.3            py27h1de35cc_0  
ptyprocess                0.5.2                    py27_0    conda-forge
pygments                  2.2.0                    py27_0    conda-forge
pyparsing                 2.2.0            py27h5bb6aaf_0  
python                    2.7.14              h138c1fe_31  
python-dateutil           2.7.2                    py27_0  
pytz                      2018.3                   py27_0  
pywavelets                0.5.2            py27hd99e88a_0  
pyyaml                    3.12             py27ha7932d0_1  
pyzmq                     17.0.0                   py27_4    conda-forge
readline                  7.0                  hc1231fa_4  
scandir                   1.7                      py27_0    conda-forge
scikit-image              0.13.0           py27h03e84e1_1  
scikit-learn              0.19.1           py27h9788993_0  
scipy                     1.0.0            py27h793f721_0  
seaborn                   0.8.1            py27h6bd0ddc_0  
send2trash                1.5.0                      py_0    conda-forge
setuptools                39.0.1                   py27_0  
simplegeneric             0.8.1                    py27_0    conda-forge
singledispatch            3.4.0.3          py27he22c18d_0  
six                       1.11.0           py27h7252ba3_1  
sortedcontainers          1.5.9                    py27_0  
sqlite                    3.22.0               h3efe00b_0  
statsmodels               0.8.0            py27h6d68dbf_0  
subprocess32              3.2.7            py27h24b2887_0  
tblib                     1.3.2            py27ha684fc4_0  
terminado                 0.8.1                    py27_0    conda-forge
testpath                  0.3.1                    py27_0    conda-forge
tk                        8.6.7                h35a86e2_3  
toolz                     0.9.0                    py27_0  
tornado                   5.0.1                    py27_1  
traitlets                 4.3.2                    py27_0    conda-forge
traittypes                0.2.1                      py_1    conda-forge
wcwidth                   0.1.7                    py27_0    conda-forge
webencodings              0.5.1                    py27_0    conda-forge
wheel                     0.30.0           py27h677a027_1  
widgetsnbextension        3.4.0                    py27_0    conda-forge
xlrd                      1.1.0            py27hbd41ed1_1  
xz                        5.2.3                h0278029_2  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.2.5                         1    conda-forge
zict                      0.1.3            py27h5fff8b1_0  
zlib                      1.2.11               hf3cbc9b_2  
