## YAML CONFIGURATION FILE FOR KCHIP

# Droplets Image Parameters
image:
  base_path: /Users/mandy/Develop/PyCharm/BPCP/kchip/Accessory/Chip24_data/

  names:
    premerge: Chip24_premerge
    t0: Chip24_t0
    t1: Chip24_t1
    t2: Chip24_t2

  pixel_size: 6.5 # um/px
  size: 1024 # px
  overlap: 0.05
  well_start_image: [1,1]
  well_start_xy: [518,434] # need to update this bsed on ChipX_premerge_1_1
  dyes: [1,3,2]  # index (start at 0) in image for dye channels
  bugs: 0       # index of bugs (start at 0) in image for dye channels

well_mask:
  filename: /Users/mandy/Develop/PyCharm/BPCP/kchip/Accessory/Well Masks/k2_mask.tif
  pixel_size: 8.33625 # um/px
  well_start_xy: [242,378] # currently this is post scaling

barcodes:
  path: /Users/mandy/Develop/PyCharm/BPCP/kchip/Accessory/Chip24_data/Notes.xlsx
  cluster:
      offset: [600,600,600]
      points_to_cluster: 2000
      eps: 0.01
      min_samples: 10
